# Generated by Django 4.2 on 2023-04-19 20:09

import datetime
from django.db import migrations, models
import number_classifier.upload_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=number_classifier.upload_image.upload_to)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 4, 19, 23, 9, 8, 21789))),
            ],
        ),
    ]
